[tool.poetry]
name = "beginner.py"
version = "0.0.41"
description = ""
authors = ["Zech Zimmerman <zechzimm@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8.0"
peewee = "^3.13"
psycopg2-binary = "^2.8"
requests = "^2.22"
google = "^2.0"
google-api-python-client = "^1.7"
numpy = "^1.19.0"
bevy = "^0.2.0"
pyyaml = "^5.3.1"
python-dateutil = "^2.8.1"
"discord.py" = "^1.5.1"
xmltodict = "^0.12.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
